#!/bin/bash
# 🚀 QUICK START GUIDE

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║         JKLG TRAVEL - QUICK START & TROUBLESHOOTING              ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CURRENT STATUS"
echo "  ✅ Router nesting error FIXED"
echo "  ✅ Dev server running on http://localhost:5174"
echo "  ✅ All contexts properly configured"
echo "  ✅ Ready for development and deployment"
echo ""

echo "🚀 QUICK COMMANDS"
echo ""
echo "Development:"
echo "  npm run dev          # Start dev server (http://localhost:5174)"
echo "  npm run build        # Build for production"
echo "  npm run preview      # Preview production build locally"
echo ""

echo "Code Quality:"
echo "  npm run lint         # Check code with ESLint"
echo "  npm run type-check   # Verify TypeScript"
echo ""

echo "📁 IMPORTANT FILES"
echo "  src/main.tsx         - Root entry (BrowserRouter here) ✅"
echo "  src/App.tsx          - App component (providers only) ✅"
echo "  src/AppRoutes.tsx    - All route definitions"
echo "  .env.example         - Environment variables template"
echo ""

echo "🔑 DEMO CREDENTIALS"
echo "  Email:    admin@jklgtravel.com"
echo "  Password: admin123"
echo ""

echo "📚 DOCUMENTATION"
echo "  README.md                  - Setup & features"
echo "  DEPLOYMENT.md              - Deployment options (5 platforms)"
echo "  APPLICATION_STATUS.md      - Current system status"
echo "  ERROR_RESOLUTION_GUIDE.md  - How the error was fixed"
echo "  BUG_FIX_REPORT.md          - Detailed technical analysis"
echo ""

echo "🔐 SECURITY"
echo "  ✅ JWT Authentication implemented"
echo "  ✅ Role-based access control (RBAC)"
echo "  ✅ Error boundary for error catching"
echo "  ✅ Input validation & sanitization"
echo "  ✅ XSS prevention active"
echo ""

echo "🌐 DEPLOYMENT OPTIONS"
echo "  1. Vercel      - npm install -g vercel && vercel --prod"
echo "  2. Netlify     - netlify deploy --prod --dir dist"
echo "  3. Docker      - docker build -t travel . && docker run -p 3000:3000 travel"
echo "  4. Traditional - See DEPLOYMENT.md"
echo "  5. GitHub Pages - npm run build && push dist/"
echo ""

echo "🆘 TROUBLESHOOTING"
echo ""
echo "Q: Port 5173 is in use"
echo "A: Dev server will automatically try port 5174"
echo ""
echo "Q: Module not found error"
echo "A: Run: rm -rf node_modules && npm install"
echo ""
echo "Q: Build fails"
echo "A: Run: npm run type-check to see TypeScript errors"
echo ""
echo "Q: How do I deploy?"
echo "A: See DEPLOYMENT.md for 5+ platform-specific guides"
echo ""

echo "📊 PROJECT STRUCTURE"
echo "  src/"
echo "  ├── pages/          - Page components (home, about, etc)"
echo "  ├── admin/          - Admin panel pages"
echo "  ├── components/     - Reusable components"
echo "  ├── contexts/       - Auth, Notifications"
echo "  ├── hooks/          - Custom React hooks"
echo "  ├── lib/            - Utilities (API, validation, logging)"
echo "  ├── App.tsx         - App component"
echo "  ├── AppRoutes.tsx   - Route definitions"
echo "  └── main.tsx        - Entry point"
echo ""

echo "✨ FEATURES AVAILABLE"
echo "  ✅ Responsive design (mobile-friendly)"
echo "  ✅ Hero carousel"
echo "  ✅ Destination showcase"
echo "  ✅ Package browser"
echo "  ✅ Photo gallery"
echo "  ✅ Testimonial slider"
echo "  ✅ Contact form"
echo "  ✅ Admin panel"
echo "  ✅ Error tracking"
echo "  ✅ Analytics ready"
echo ""

echo "🔄 DEVELOPMENT WORKFLOW"
echo "  1. npm run dev      # Start development server"
echo "  2. Make changes     # Edit files"
echo "  3. Hot reload       # Changes auto-reload (Vite)"
echo "  4. npm run lint     # Check code quality"
echo "  5. npm run build    # Build for production"
echo "  6. Deploy           # Push to your platform"
echo ""

echo "🎯 NEXT STEPS"
echo "  1. Configure .env with your Supabase credentials"
echo "  2. npm install (if needed)"
echo "  3. npm run dev"
echo "  4. Visit http://localhost:5174"
echo "  5. Test the application"
echo "  6. Run npm run build"
echo "  7. Deploy using DEPLOYMENT.md guide"
echo ""

echo "📞 SUPPORT"
echo "  💻 Development: Check console errors (F12)"
echo "  📖 Setup issues: See README.md"
echo "  🚀 Deployment: See DEPLOYMENT.md"
echo "  🔐 Security: See SECURITY.md"
echo "  👨‍💻 Contributing: See CONTRIBUTING.md"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║  Application is PRODUCTION READY! Ready to deploy? 🚀            ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
